const productos = [
    { id: 1, nombre: "Remera lisa negra-hombre", precio: 5000, img: "remera-negra.jpg" },
    { id: 2, nombre: "Remera lisa blanca-hombre", precio: 5000, img: "remera-blanca.jpg" },
    { id: 3, nombre: "Camisa manga larga-hombre", precio: 20000, img: "camisa.jpg" },
    { id: 4, nombre: "Camisa manga corta-hombre", precio: 15000, img: "camisa-corta.jpg" },
    { id: 5, nombre: "Chomba-hombre", precio: 7500, img: "chomba.jpg" },
    { id: 6, nombre: "Jeans-hombre", precio: 15000, img: "jeans-azul.png" },
    { id: 7, nombre: "Buzo térmico-hombre", precio: 10000, img: "buzo-micropolar.jpg" },
    { id: 8, nombre: "Buzo canguro-hombre", precio: 12000, img: "canguro.jpg" },
    { id: 9, nombre: "Conjunto deportivo-hombre", precio: 8000, img: "conjunto-deportivo.jpg" },
    { id: 10, nombre: "Jogging-hombre", precio: 9500, img: "jogging.jpg" },
    { id: 11, nombre: "Blusa roja-muje", precio: 12500, img: "blusa-roja.jpg" },
    { id: 12, nombre: "Pantalón engomado-mujer", precio: 15000, img: "pantalon-engomado.jpg" },
    { id: 13, nombre: "Top deportivo-mujer", precio: 5500, img: "top-deportivo.jpg" },
    { id: 14, nombre: "Vestido de fiesta-mujer", precio: 18000, img: "vestido-fiesta.jpg" },
    { id: 15, nombre: "Remera térmica manga corta-mujer", precio: 6000, img: "remera-termica-manga-corta.jpg" },
    { id: 16, nombre: "Enterito-niña", precio: 10000, img: "enterito-niña.jpg" },
    { id: 17, nombre: "Camisa a cuadros-niño", precio: 11500, img: "camisa-niño.jpg" },
    { id: 18, nombre: "Conjunto de baño-niña", precio: 9000, img: "conjunto-baño.jpg" },
    { id: 19, nombre: "Remera-niño", precio: 5000, img: "remeras-niño.jpg" },
    { id: 20, nombre: "Vestido de fiesta-niña", precio: 30000, img: "vestido-de-fiesta-para-nina.jpg" }
]